### ISSUE TITLE
This always throws an error and I have to go edit, would it cause any issues to change it?

### ISSUE THREAD

**Issue by murpg** [michaelborn/UpChunk#4]
On the upchunk model you are implmenting IChunk.  It always error and says IChunk  cannot be found.
```
component
    implements="upchunk.models.IChunk"
    accessors ="true"
    singleton
{
I have to change it to this.
component
    implements="IChunk"
    accessors ="true"
    singleton
{
```
Are you able to please change it?

**Comment by michaelborn** [comment]
So sorry I missed this, @murpg ! Your PR is merged and v2.1.0 is out, so this should be all set.
